#!/usr/bin/env python

import json

from fmi import FMI

class Cron:

    def __init__(self):
        self.config = json.load(open('config.json'))
        self.fmi = FMI(self.config['username'], self.config['password'])

    def fetch(self):
        self.fmi.login()
            
        # fetch last positions
        latest = self.fmi.devices()

        for device in latest['content']:
            if not device['location']:
                continue
            print device['name'],
            print device['location']['longitude'],
            print device['location']['latitude']
        
        # send updates
        for device in self.config['devices']:
            self.fmi.devices(locate=device)

def main():
    Cron().fetch()

if __name__ == '__main__':
    main()
