#!/usr/bin/env python

import os
import json
import time

ROOT = os.path.abspath(os.path.dirname(__file__))
os.chdir(ROOT)

from fmi import FMI
from db import *


class Cron:

    def __init__(self):
        self.config = json.load(open('config.json'))
        self.fmi = FMI(
            self.config['me']['username'],
            self.config['me']['password'],
            )

    def fetch(self):
        self.fmi.login()
            
        # fetch last positions
        latest = self.fmi.devices()

        for device in latest['content']:
            if not device['location']:
                continue

            self.process_device(device)
        
        session.commit()

    def process_device(self, device_info):
        name = device_info['name']
        long = device_info['location']['longitude']
        lat = device_info['location']['latitude']
        device = Device.get_by_name(name)
        
        sample = Sample(device=device, ts=int(time.time()),
            long=long, lat=lat)


    def update(self):
        
        # send updates
        for device in self.config['devices']:
            self.fmi.devices(locate=device)

def main():
    c = Cron()
    c.fetch()
    c.update()

if __name__ == '__main__':
    main()
