#!/usr/bin/env python

import json

import heatmap

from db import *

class DumpHeatmap:

    def __init__(self):
        self.config = json.load(open('config.json'))

    def run(self):
        hm = heatmap.Heatmap()
        pts = []
        for sample in Sample.query.all():
            pts.append((sample.long, sample.lat))
        hm.heatmap(pts, "classic.png")
        hm.saveKML("data.kml")

def main():
    d = DumpHeatmap()
    d.run()

if __name__ == '__main__':
    main()



