#!/usr/bin/env python
# -*- coding: utf-8 -*-

from datetime import *
import json

from db import *

class Dump:

    def __init__(self):
        self.config = json.load(open('config.json'))

    def header(self):
        print 'name,ts,longitude,latitude,humanago'

    def dump_all(self):
        for device in Device.query.all():
            self.dump_device(device)

    def dump_device(self, device):
        for sample in Sample.query.filter_by(device=device):
            h = datetime.fromtimestamp(sample.ts)
            s = '%s,%i,%f,%f,%s' % (
                device.name,
                sample.ts,
                sample.long,
                sample.lat,
                datetime.now() - h
                )
            s = s.encode('utf8')
            print s

def main():
    d = Dump()
    d.header()
    d.dump_all()

if __name__ == '__main__':
    main()


